
local CONSTANTS = gKarts.Constants or {}
gKarts.Constants = CONSTANTS

CONSTANTS.KART_GRAVITY_STICK_DISTANCE = Vector(0, 0, -40)

CONSTANTS.KART_MASS = 600

CONSTANTS.KART_HOVER_HEIGHT = 2
CONSTANTS.KART_HOVER_FORCE = 1200

CONSTANTS.KART_STEERING_SENSITIVITY = 4
CONSTANTS.KART_THROTTLE_SENSITIVITY = 4

CONSTANTS.KART_STEER_FORCE_ORIGIN = Vector(0, 31, 5)
