name: BuildModule
on: [push]
jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd module
      - run: sudo apt-get update && sudo apt-get install -y g++-9-multilib
      - run: wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-linux.tar.gz
      - run: tar -zxvf premake-5.0.0-alpha15-linux.tar.gz
      - run: premake5 gmake
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "QuizAPI"
          files: |
            module/*